site_name: CMPUT 401 Course Docs
theme: readthedocs
nav:
  - Main Information:
    - "Course Description": "index.md"
    - "Course Outline": "course-outline.md"
    - "Course Policies": "course-policies.md"
    - "Teaching Team": "teaching-team.md"

  - Indvidual Work:
    - "Marking Individual Work": "marking-individual.md"

  - Project Marking:
    - "Project Expectations": "project-expectations.md"
    - "Sprint 1": "marking-sprint1.md"
    - "Sprint 2": "marking-sprint2.md"
    - "Sprint 3": "marking-sprint3.md"
    - "Sprint 4": "marking-sprint4.md"
    - "Sprint 5": "marking-sprint5.md"
    - "Presentation": "marking-presentation.md"
    - "Screencast": "marking-screencast.md"
    - "Client Feedback": "marking-client-feedback.md"

  - Reference Materials:
    # - "Meeting Minutes Example": "meeting-minutes-example.md"
    - "Links": "links.md"
    - "Resources": "resources.md"

markdown_extensions:
  - admonition
  - attr_list
